from django.conf.urls.defaults import *
from facbycar.apps.views import *
from django.contrib.auth.views import logout

urlpatterns = patterns('',
	
	url(r'^$', home, name='home'),
	url(r'^register/$', register, name='register'),
	url(r'^add_car/$', add_car, name='add_car'),
	url(r'^edit_car/$', edit_car, name='edit_car'),
	url(r'^edit_car2/$', edit_car2, name='edit_car2'),
	url(r'^del_car/$', del_car, name='del_car'),
	url(r'^car/$', car, name='car'),
	url(r'^search/$', search, name='search'),
	url(r'^edit_profile/$', edit_profile, name='edit_profile'),
	url(r'^profile/$', profile, name='profile'),
	url(r'^user_profile/$', user_profile, name='user_profile'),
	url(r'^add_route/$', add_route1, name='add_route1'),
	url(r'^add_route2/$', add_route2, name='add_route2'),
	url(r'^add_route3/$', add_route3, name='add_route3'),
	url(r'^summary/$', summary, name='summary'),
	url(r'^my_routes/$', my_routes, name='my_routes'),
	url(r'^my_demands/$', my_demands, name='my_demands'),
	url(r'^basic_search/$', basic_search, name='basic_search'),
	url(r'^refined_search/$', refined_search, name='refined_search'),
	url(r'^last_routes/$', last_routes, name='last_routes'),
	url(r'^ads_time/$', ads_time, name='ads_time'),
	url(r'^ads_price/$', ads_price, name='ads_price'),
	url(r'^login/$', login, name='login'),
	url(r'^logout/$', logout, {'template_name': 'apps/home.html'}),
	url(r'^send_message/$', send_message, name='send_message'),
	url(r'^read_message/$', read_message, name='read_message'),
	url(r'^messages/$', messages, name='messages'),
	url(r'^sended_messages/$', sended_messages, name='sended_messages'),
	url(r'^faq/$', faq, name='faq'),
	url(r'^charte/$', charte, name='charte'),
	url(r'^plan_du_site/$', plan_du_site, name='plan_du_site'),
	url(r'^mentions_legales/$', mentions_legales, name='mentions_legales'),
	url(r'^contact/$', contact, name='contact'),
	url(r'^delete_message/$', delete_message, name='delete_message'),
	url(r'^route/$', route, name='route'),
	#url(r'^confirmation/$', confirmation, name='confirmation'),
)
