from django.conf.urls.defaults import *
from facbycar.apps.views import *
from django.contrib.auth.views import logout
from django.contrib.auth import views as auth_views

urlpatterns = patterns('',
	
	url(r'^$', home, name='home'),
	url(r'^register/$', register, name='register'),
	url(r'^activate/(?P<activation_key>\w+)/$', activate, name='registration_activate'),
	url(r'^password/change/$',auth_views.password_change,name='auth_password_change'),
	url(r'^password/reset/$',auth_views.password_reset,name='auth_password_reset'),
	url(r'^password/reset/confirm/(?P<uidb36>[0-9A-Za-z]+)-(?P<token>.+)/$',auth_views.password_reset_confirm,name='auth_password_reset_confirm'),
	url(r'^password/reset/confirm/$',auth_views.password_reset_complete,name='auth_views.password_reset_complete'),
	url(r'^password/reset/complete/$',auth_views.password_reset_complete,name='auth_password_reset_complete'),
	url(r'^password/reset/done/$',auth_views.password_reset_done,name='auth_password_reset_done'),
	url(r'^add_car/$', add_car, name='add_car'),
	url(r'^edit_car/$', edit_car, name='edit_car'),
	url(r'^edit_car2/$', edit_car2, name='edit_car2'),
	url(r'^edit_route/$', edit_route, name='edit_route'),
	# url(r'^edit_route1/$', edit_route1, name='edit_route1'),
	# url(r'^edit_route2/$', edit_route2, name='edit_route2'),
	# url(r'^edit_route3/$', edit_route3, name='edit_route3'),
	url(r'^del_car/$', del_car, name='del_car'),
	url(r'^car/$', car, name='car'),
	url(r'^search/$', search, name='search'),
	url(r'^edit_profile/$', edit_profile, name='edit_profile'),
	url(r'^profile/$', profile, name='profile'),
	url(r'^user_profile/$', user_profile, name='user_profile'),
	url(r'^add_route/$', add_route1, name='add_route1'),
	url(r'^add_route2/$', add_route2, name='add_route2'),
	url(r'^add_route3/$', add_route3, name='add_route3'),
	url(r'^summary/$', summary, name='summary'),
	url(r'^my_routes/$', my_routes, name='my_routes'),
	url(r'^my_demands/$', my_demands, name='my_demands'),
	url(r'^basic_search/$', basic_search, name='basic_search'),
	url(r'^refined_search/$', refined_search, name='refined_search'),
	url(r'^last_routes/$', last_routes, name='last_routes'),
	url(r'^ads_time/$', ads_time, name='ads_time'),
	url(r'^ads_price/$', ads_price, name='ads_price'),
	url(r'^login/$', login, name='login'),
	url(r'^logout/$', logout, {'template_name': 'apps/home.html'}),
	url(r'^send_message/$', send_message, name='send_message'),
	url(r'^read_message/$', read_message, name='read_message'),
	url(r'^messages/$', messages, name='messages'),
	url(r'^sended_messages/$', sended_messages, name='sended_messages'),
	url(r'^delete_message/$', delete_message, name='delete_message'),
	url(r'^delete_message_confirmation/$', delete_message_confirmation, name='delete_message'),
	url(r'^user_search/$', user_search, name='user_search'),
	url(r'^user_contacts_list/$', user_contacts_list, name='user_contacts_list'),
	url(r'^add_contact_to_list/$', add_contact_to_list, name='add_contact_to_list'),
	url(r'^del_contact_to_list/$', del_contact_to_list, name='del_contact_to_list'),
	url(r'^reply_message/$', reply_message, name='reply_message'),
	url(r'^faq/$', faq, name='faq'),
	url(r'^charte/$', charte, name='charte'),
	url(r'^plan_du_site/$', plan_du_site, name='plan_du_site'),
	url(r'^mentions_legales/$', mentions_legales, name='mentions_legales'),
	url(r'^contact/$', contact, name='contact'),
	url(r'^route/$', route, name='route'),
	#url(r'^confirmation/$', confirmation, name='confirmation'),
)

